### ISSUE TITLE
Ruby 2.1.7

### ISSUE THREAD

**Issue by felixbuenemann** [brightbox/deb-ruby2.1#13]
[Ruby 2.1.7](https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-1-7-released/) is missing here and from the upstream debian repo.

Could you still package it in the brighbox repo?

I've already build debs for debian wheezy and had no trouble updating the packages to 2.1.7.

**Comment by felixbuenemann** [comment]
@johnl If you prefer a PR, let me know.

**Comment by johnl** [comment]
no PR needed, this is just fine thanks. Builds on the way, I'll close when the tests pass and I release: https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng-experimental/+builds?build_text=&build_state=all

**Comment by felixbuenemann** [comment]
Thanks, John!

**Comment by sodabrew** [comment]
:apple:
