### ISSUE TITLE
ruby 2.1.x for Ubuntu Lucid Lynx (10.04 LTS)?

### ISSUE THREAD

**Issue by mminks** [brightbox/deb-ruby2.1#4]
John, your blog post from January 9th states, that Lucid Lynx packages for ruby 2.1 will be available soon. Is it possible to built these packages?

**Comment by felixbuenemann** [comment]
I think this issue can be closed…

**Comment by johnl** [comment]
yep, got ruby2.1 and ruby2.0 packages for lucid now. closing.
